### ISSUE TITLE
camera rendered null image

### ISSUE THREAD

**Issue by mxp1234** [cyliizyz/ManiSkill-ViTac2025#2]
I try to get the scene image on the remote server, but it always returns a white transparent image, as below：
```
[[[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  ...
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]
......
```
I have checked：
1. add the scene light
2. Image acquisition process：
```
 env.scene.step()
 env.scene.update_render()  # sync pose from SAPIEN to renderer
 env.camera.take_picture() 
rgba = env.camera.get_picture("Color")
''''
```
3. Camera pose（I'm not sure if that's the problem here，i also try the reference pose from the code）
```
 self.camera.entity.set_pose(sapien.Pose( [-0.0477654, 0.0621954, 0.086787],
                    [0.846142, 0.151231, 0.32333, -0.395766],))
```

4. all entities are added in scene

Hope to get some tips

**Comment by mxp1234** [comment]
solved

**Comment by DrTrippleJ** [comment]
> solved

Sorry for the late response. Could you please tell us how you solved the problem? This might help someone else.
